# Generated by Django 3.1.2 on 2021-06-28 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('station_type', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('county', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40)),
                ('sample_code', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('depth', models.FloatField()),
                ('depth_units', models.CharField(max_length=15)),
                ('parameter', models.CharField(max_length=40)),
                ('result', models.FloatField()),
                ('reporting_limit', models.FloatField()),
                ('units', models.CharField(max_length=20)),
                ('method_name', models.CharField(max_length=40)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.station')),
            ],
        ),
    ]
