# Generated by Django 3.1.2 on 2021-07-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresult',
            name='method_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='parameter',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
