# Generated by Django 3.1.2 on 2021-07-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresult',
            name='depth',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='reporting_limit',
            field=models.FloatField(null=True),
        ),
    ]
